install.packages("wordcloud")
library(wordcloud)
install.packages("tm")
library(tm)
data <- read.csv("dataset.csv")
text <- data$summary
docs <- Corpus(VectorSource(text))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, removeWords, c("paper", "can", "two", "one"))
dtm <- TermDocumentMatrix(docs)
matrix <- as.matrix(dtm)
words <- sort(rowSums(matrix), decreasing = TRUE)
df <- data.frame(word = names(words), freq = words)
wordcloud(words = df$word, freq = df$freq, min.freq = 5, max.words = 50, random.order = FALSE, colors = brewer.pal(8, "Accent"))
counts <- table(data$category)
barplot(head(sort(counts, decreasing = TRUE), n = 15), main = "Категории", xlab = "Категории", ylab = "Количество статей")